#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2026 vivo Mobile Communication Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Compile a generated app-package manifest into a static kernel catalog.

The output is a no_std Rust source defining the package manifest types and a
`PACKAGES` static: the exact frozen view the kernel resolver consumes (C30,
§6.1). Each image also names its embedded `.bk_seed` blob symbol pair (derived
from its VFS path) and a helper to read its bytes, so the boot seed can copy
the package into the root tmpfs.

Usage: gen_app_package_catalog.py --manifest <json> --out <catalog.rs>
"""

import argparse
import json
import re
import sys


def sanitize_ident(path):
    """Derive a C/Rust identifier from a VFS path."""
    ident = re.sub(r"[^0-9A-Za-z_]", "_", path).strip("_")
    return ident or "root"


def hex_bytes(hexstr):
    return bytes.fromhex(hexstr)


def byte_array(data, indent):
    body = ", ".join(str(b) for b in data)
    return f"[{body}]"


def rust_str(value, indent):
    # Render a byte slice as a Rust `b"..."` literal (ASCII-escaped).
    body = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'b"{body}"'


def emit(manifests, handle):
    """Emit the whole catalog: shared types once, every package's images, and
    one aggregated `PACKAGES` static."""

    handle.write("// Generated by gen_app_package_catalog.py — do not edit.\n")
    handle.write("#![no_std]\n")
    # The PKG_IMAGE_* statics inherit the blob symbol idents, which must stay
    # byte-identical with the seed ASM generator's sanitization.
    handle.write("#![allow(non_upper_case_globals)]\n\n")

    handle.write("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n")
    handle.write("pub enum PackageImageRole { Root, PrivateDso }\n\n")
    handle.write("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n")
    handle.write("pub enum DependencySource { PackagePrivate, System }\n\n")
    handle.write("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n")
    handle.write("pub struct DeclaredDependency {\n")
    handle.write("    pub soname: &'static [u8],\n")
    handle.write("    pub source: DependencySource,\n")
    handle.write("}\n\n")
    handle.write("#[derive(Clone, Copy, PartialEq, Eq)]\n")
    handle.write("pub struct PackageImageEntry {\n")
    handle.write("    pub role: PackageImageRole,\n")
    handle.write("    pub path: &'static str,\n")
    handle.write("    pub soname: Option<&'static [u8]>,\n")
    handle.write("    pub build_id: &'static [u8],\n")
    handle.write("    pub needed: &'static [DeclaredDependency],\n")
    handle.write("}\n\n")
    handle.write("pub struct ApplicationPackageManifest {\n")
    handle.write("    pub package_id: &'static [u8],\n")
    handle.write("    pub profile: &'static str,\n")
    handle.write("    pub root: PackageImageEntry,\n")
    handle.write("    pub private_images: &'static [&'static PackageImageEntry],\n")
    handle.write("    pub system_sonames: &'static [&'static [u8]],\n")
    handle.write("}\n\n")

    packages = []  # (package_id, profile, root_ident, private_idents, system)
    all_entries = []  # (ident, path) across every package

    for manifest in manifests:
        package_id = manifest["package_id"]
        root = manifest["root"]
        privates = manifest["private_images"]
        system = manifest.get("system_sonames", [])

        entries = []
        for entry in [root] + privates:
            needed = entry["needed"]
            deps = ", ".join(
                "DeclaredDependency {{ soname: {}, source: DependencySource::{} }}".format(
                    rust_str(edge["soname"], 0),
                    "PackagePrivate" if edge["source"] == "package" else "System",
                )
                for edge in needed
            )
            role = "PackageImageRole::Root" if entry["role"] == "root" \
                else "PackageImageRole::PrivateDso"
            soname = "Some({})".format(rust_str(entry["soname"], 0)) \
                if entry["soname"] else "None"
            ident = sanitize_ident(entry["path"])
            entries.append((ident, entry, role, soname, deps))
            all_entries.append((ident, entry["path"]))

        root_ident = next(ident for ident, entry, _, _, _ in entries
                          if entry["role"] == "root")
        private_list = ", ".join(
            "&PKG_IMAGE_{}".format(ident) for ident, entry, _, _, _ in entries
            if entry["role"] != "root"
        )
        packages.append((package_id, manifest["profile"], root_ident,
                         private_list, system))

        # The embedded blob symbol pairs.
        handle.write("extern \"C\" {\n")
        for ident, _, _, _, _ in entries:
            handle.write("    static __bk_seed_{}_start: u8;\n".format(ident))
            handle.write("    static __bk_seed_{}_end: u8;\n".format(ident))
        handle.write("}\n\n")

        for ident, entry, role, soname, deps in entries:
            handle.write("static PKG_IMAGE_{}: PackageImageEntry = PackageImageEntry {{\n"
                         .format(ident))
            handle.write("    role: {},\n".format(role))
            handle.write("    path: \"{}\",\n".format(entry["path"]))
            handle.write("    soname: {},\n".format(soname))
            handle.write("    build_id: &{},\n".format(byte_array(
                hex_bytes(entry["build_id"]), 4)))
            handle.write("    needed: &[{}],\n".format(deps))
            handle.write("};\n\n")

    handle.write("pub static PACKAGES: &[ApplicationPackageManifest] = &[\n")
    for package_id, profile, root_ident, private_list, system in packages:
        system_list = ", ".join(rust_str(name, 0) for name in system)
        handle.write("    ApplicationPackageManifest {\n")
        handle.write("        package_id: {},\n".format(rust_str(package_id, 0)))
        handle.write("        profile: \"{}\",\n".format(profile))
        handle.write("        root: PKG_IMAGE_{},\n".format(root_ident))
        handle.write("        private_images: &[{}],\n".format(private_list))
        handle.write("        system_sonames: &[{}],\n".format(system_list))
        handle.write("    },\n")
    handle.write("];\n\n")

    # Blob access helper: the boot seed copies each image by its VFS path.
    handle.write("/// The embedded bytes of the package image at `path`, if any.\n")
    handle.write("///\n")
    handle.write("/// # Safety\n")
    handle.write("/// The `.bk_seed` blob pairs bound linker-emitted artifact bytes.\n")
    handle.write("pub unsafe fn image_blob(path: &str) -> Option<&'static [u8]> {\n")
    for ident, path in all_entries:
        handle.write("    if path == \"{}\" {{\n".format(path))
        handle.write("        let start = &__bk_seed_{}_start as *const u8;\n".format(ident))
        handle.write("        let end = &__bk_seed_{}_end as *const u8;\n".format(ident))
        handle.write("        let len = (end as usize).wrapping_sub(start as usize);\n")
        handle.write("        return Some(core::slice::from_raw_parts(start, len));\n")
        handle.write("    }\n")
    handle.write("    None\n")
    handle.write("}\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", action="append", required=True,
                        help="package manifest JSON (repeatable)")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    manifests = []
    for path in args.manifest:
        with open(path, encoding="utf-8") as handle:
            manifests.append(json.load(handle))
    with open(args.out, "w", encoding="utf-8") as handle:
        emit(manifests, handle)
    print(f"gen_app_package_catalog: wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
