#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2026 vivo Mobile Communication Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate an assembly file embedding dynamic artifacts for boot seeding.

Each `--blob <symbol>,<path>` pair emits a start/end symbol pair around an
`.incbin` of the artifact, so the kernel can copy the bytes into the root
tmpfs at boot (C29, §18.1/18.2). An optional `--layout <json>` adds every app
bundle image with a symbol derived from its VFS path — the same naming rule
`gen_boot_seed_catalog.py` uses. The emitted directives are
architecture-neutral; the output is assembled with the board kernel config
and linked into every kernel image that depends on the blueos crate.

Usage: gen_seed_blob_asm.py --out <file.S> \
          --blob hello,/abs/path/bin/hello \
          --blob libc,/abs/path/lib/liblibrs.so \
          [--layout /abs/path/app_layout.json]
"""

import argparse
import hashlib
import json
import os
import re


def sanitize_ident(path):
    ident = re.sub(r"[^0-9A-Za-z_]", "_", path).strip("_")
    return ident or "root"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument("--blob", action="append", default=[],
                        help="symbol,path pair to embed")
    parser.add_argument("--layout", action="append", default=[],
                        help="app layout JSON (vfs_path/artifact, repeatable)")
    args = parser.parse_args()

    blobs = []
    for spec in args.blob:
        symbol, _, path = spec.partition(",")
        if not symbol or not path or not os.path.isfile(path):
            raise SystemExit("gen_seed_blob_asm: missing artifact for "
                             f"blob {spec!r}")
        blobs.append((symbol, path))

    for layout_path in args.layout:
        with open(layout_path, encoding="utf-8") as handle:
            layout = json.load(handle)
        for item in layout:
            vfs_path = item["vfs_path"]
            artifact = item["artifact"]
            if not os.path.isfile(artifact):
                raise SystemExit(
                    f"gen_seed_blob_asm: layout artifact missing: {artifact}")
            blobs.append((sanitize_ident(vfs_path), artifact))

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write("// Generated by gen_seed_blob_asm.py — do not edit.\n")
        # A per-blob content digest in the emitted text: ninja's restat sees
        # changed text when an embedded artifact changes, so the assembler
        # re-runs and the kernel images embed the fresh bytes (the .incbin
        # targets are invisible to ninja otherwise).
        for symbol, path in blobs:
            digest = hashlib.sha256(open(path, "rb").read()).hexdigest()[:16]
            handle.write(f"// blob {symbol}: {digest}\n")
        handle.write("    .section .bk_seed,\"a\",%progbits\n")
        for symbol, path in blobs:
            handle.write("    .balign 16\n")
            handle.write(f"    .global __bk_seed_{symbol}_start\n")
            handle.write(f"__bk_seed_{symbol}_start:\n")
            handle.write(f"    .incbin \"{path}\"\n")
            handle.write(f"    .global __bk_seed_{symbol}_end\n")
            handle.write(f"__bk_seed_{symbol}_end:\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
