#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2026 vivo Mobile Communication Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate the Rust source for a per-image boot application profile provider.

The output is a tiny no_std rlib that defines exactly one
``__BLUEOS_BOOT_APPLICATION_PROFILE`` symbol.  The kernel's ``boot.rs``
reads it at boot to decide whether to install the embedded ELF seed,
initialize the dynamic runtime, and how to start the first application.

This is an internal linking ABI — not a user-visible syscall contract.
See ``book/src/dynamic-loading-boot-mode-refactor-plan.md`` §6.2.
"""

import argparse

# --- ABI constants (must match kernel/boot_profile/src/lib.rs) ----------

ABI_VERSION = 1

FLAG_DYNAMIC_LOADER = 1 << 0
FLAG_IMPORT_EMBEDDED_ELF = 1 << 1

MODE_STATIC = 1
MODE_DYNAMIC = 2
MODE_NONE = 3

_MODE_MAP = {
    "static": MODE_STATIC,
    "dynamic": MODE_DYNAMIC,
    "none": MODE_NONE,
}


def emit(args, output):
    mode = _MODE_MAP[args.application_start]

    flags = 0
    if args.enable_dynamic_loader:
        flags |= FLAG_DYNAMIC_LOADER
    if args.import_embedded_dynamic_elf:
        flags |= FLAG_IMPORT_EMBEDDED_ELF

    # Encode the dynamic root path as a static byte slice so the profile
    # struct holds a pointer + length, both 'static.
    path_bytes = args.dynamic_root_path.encode("utf-8") if args.dynamic_root_path else b""
    path_len = len(path_bytes)

    path_literal = "".join(f"\\x{b:02x}" for b in path_bytes)

    with open(output, "w", encoding="utf-8") as handle:
        handle.write("// Generated by gen_blueos_boot_profile.py — do not edit.\n")
        handle.write("#![no_std]\n#![allow(non_upper_case_globals)]\n\n")
        handle.write(
            "// The boot application profile (§6.2).  Exactly one of these "
            "must be linked into every bootable kernel image.\n"
        )
        handle.write(
            f"const _DYNAMIC_ROOT_PATH: &[u8] = b\"{path_literal}\";\n"
            if path_literal
            else "const _DYNAMIC_ROOT_PATH: &[u8] = &[];\n"
        )
        handle.write("\n")
        handle.write("#[no_mangle]\n")
        handle.write("pub static __BLUEOS_BOOT_APPLICATION_PROFILE: ")
        handle.write("BootApplicationProfile = BootApplicationProfile {\n")
        handle.write(f"    abi_version: {ABI_VERSION},\n")
        handle.write(
            f"    struct_size: core::mem::size_of::<BootApplicationProfile>() as u32,\n"
        )
        handle.write(f"    mode: BootApplicationMode::from_u32({mode}),\n")
        handle.write(f"    flags: {flags},\n")
        if path_len > 0:
            handle.write(
                "    dynamic_path: _DYNAMIC_ROOT_PATH.as_ptr(),\n"
            )
        else:
            handle.write("    dynamic_path: core::ptr::null(),\n")
        handle.write(f"    dynamic_path_len: {path_len},\n")
        handle.write("};\n\n")

        # Re-export the ABI types so the provider crate does not need a
        # separate dependency on kernel/boot_profile for the struct
        # definition.  The kernel reads the symbol through the
        # boot_profile crate's extern definition, so the types here only
        # need to be layout-compatible.
        handle.write(
            "#[repr(C)]\n"
            "pub struct BootApplicationProfile {\n"
            "    pub abi_version: u32,\n"
            "    pub struct_size: u32,\n"
            "    pub mode: BootApplicationMode,\n"
            "    pub flags: u32,\n"
            "    pub dynamic_path: *const u8,\n"
            "    pub dynamic_path_len: usize,\n"
            "}\n\n"
            "#[repr(u32)]\n"
            "pub struct BootApplicationMode(u32);\n\n"
            "impl BootApplicationMode {\n"
            "    pub const fn from_u32(v: u32) -> Self { Self(v) }\n"
            "}\n\n"
            "unsafe impl Sync for BootApplicationProfile {}\n"
        )


def main():
    parser = argparse.ArgumentParser(
        description="Generate a boot application profile provider source file."
    )
    parser.add_argument(
        "--application-start",
        required=True,
        choices=["static", "dynamic", "none"],
        help="How the first application starts.",
    )
    parser.add_argument(
        "--enable-dynamic-loader",
        action="store_true",
        help="Compile and initialize the dynamic application runtime.",
    )
    parser.add_argument(
        "--import-embedded-dynamic-elf",
        action="store_true",
        help="Embed build-time ELF/DSO bytes and seed them into the VFS at boot.",
    )
    parser.add_argument(
        "--dynamic-root-path",
        default="",
        help="VFS path of the dynamic root ELF (required for mode=dynamic).",
    )
    parser.add_argument("--out", required=True, help="Output .rs file path.")
    args = parser.parse_args()

    # --- config-combination assertions (§6.3) -------------------------------
    if args.application_start == "dynamic":
        assert args.enable_dynamic_loader, (
            "application_start=dynamic requires enable_dynamic_loader"
        )
        assert args.dynamic_root_path, (
            "application_start=dynamic requires dynamic_root_path"
        )
    if args.import_embedded_dynamic_elf:
        assert args.enable_dynamic_loader, (
            "import_embedded_dynamic_elf requires enable_dynamic_loader"
        )

    emit(args, args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
