#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2026 vivo Mobile Communication Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate a no_std catalog for layout-backed boot seed blobs."""

import argparse
import json
import re


def sanitize_ident(path):
    return re.sub(r"[^0-9A-Za-z_]", "_", path).strip("_") or "root"


def emit(layouts, output):
    entries = []
    seen = set()
    for layout_path in layouts:
        with open(layout_path, encoding="utf-8") as handle:
            for item in json.load(handle):
                path = item["vfs_path"]
                if path in seen:
                    raise SystemExit(f"duplicate boot seed VFS path: {path}")
                seen.add(path)
                entries.append((path, sanitize_ident(path)))

    with open(output, "w", encoding="utf-8") as handle:
        handle.write("// Generated by gen_boot_seed_catalog.py — do not edit.\n")
        handle.write("#![no_std]\n#![allow(non_snake_case)]\n\n")
        handle.write("pub struct BootSeedFile {\n")
        handle.write("    pub path: &'static str,\n")
        handle.write("    bytes: unsafe fn() -> &'static [u8],\n")
        handle.write("}\n\n")
        handle.write("impl BootSeedFile {\n")
        handle.write("    pub unsafe fn bytes(&self) -> &'static [u8] {\n")
        handle.write("        unsafe { (self.bytes)() }\n")
        handle.write("    }\n")
        handle.write("}\n\n")
        for _, ident in entries:
            handle.write("extern \"C\" {\n")
            handle.write(f"    static __bk_seed_{ident}_start: u8;\n")
            handle.write(f"    static __bk_seed_{ident}_end: u8;\n")
            handle.write("}\n")
            handle.write(f"unsafe fn bytes_{ident}() -> &'static [u8] {{\n")
            handle.write(f"    let start = &__bk_seed_{ident}_start as *const u8;\n")
            handle.write(f"    let end = &__bk_seed_{ident}_end as *const u8;\n")
            handle.write("    let len = (end as usize).wrapping_sub(start as usize);\n")
            handle.write("    unsafe { core::slice::from_raw_parts(start, len) }\n")
            handle.write("}\n\n")
        handle.write("pub static FILES: &[BootSeedFile] = &[\n")
        for path, ident in entries:
            handle.write(
                f"    BootSeedFile {{ path: {json.dumps(path)}, bytes: bytes_{ident} }},\n")
        handle.write("];\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--layout", action="append", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    emit(args.layout, args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
