#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2026 vivo Mobile Communication Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate the embedded files and Rust catalog used by boot seeding.

Each `--file <VFS path>,<artifact>` pair and each entry from an optional
`--layout <json>` describes one file. The generated assembly embeds its bytes
between a start/end symbol pair, while the generated Rust catalog maps that
same pair to its VFS path. The kernel copies the catalog into the root tmpfs at
boot. The assembly directives are architecture-neutral and are assembled with
the board kernel config.

Usage: gen_boot_seed_files.py --asm-out <file.S> --catalog-out <file.rs> \
          --file /apps/hello/app.elf,/abs/path/bin/hello \
          --file /system/lib/libc.so.1,/abs/path/lib/liblibrs.so \
          [--layout /abs/path/app_layout.json]
"""

import argparse
import hashlib
import json
import os
import re


def sanitize_ident(path):
    ident = re.sub(r"[^0-9A-Za-z_]", "_", path).strip("_")
    return ident or "root"


def parse_file(spec):
    vfs_path, separator, artifact = spec.partition(",")
    if not separator or not vfs_path.startswith("/") or not artifact:
        raise SystemExit(f"invalid VFS path,artifact pair: {spec!r}")
    if not os.path.isfile(artifact):
        raise SystemExit(f"boot seed artifact missing: {artifact}")
    return {"vfs_path": vfs_path, "artifact": artifact}


def collect_entries(files, layouts):
    entries = [parse_file(spec) for spec in files]

    for layout_path in layouts:
        with open(layout_path, encoding="utf-8") as handle:
            layout = json.load(handle)
        for item in layout:
            entries.append(parse_file(f'{item["vfs_path"]},{item["artifact"]}'))

    paths = [entry["vfs_path"] for entry in entries]
    if len(paths) != len(set(paths)):
        raise SystemExit("duplicate boot seed VFS path")

    symbols = [sanitize_ident(path) for path in paths]
    if len(symbols) != len(set(symbols)):
        raise SystemExit("boot seed VFS paths produce duplicate symbols")
    return entries


def write_assembly(entries, output):
    with open(output, "w", encoding="utf-8") as handle:
        handle.write("// Generated by gen_boot_seed_files.py — do not edit.\n")
        # A per-file content digest in the emitted text lets ninja's restat
        # notice artifact changes. The .incbin targets are otherwise invisible
        # to the assembler edge.
        for entry in entries:
            with open(entry["artifact"], "rb") as artifact:
                digest = hashlib.sha256(artifact.read()).hexdigest()[:16]
            handle.write(f'// file {entry["vfs_path"]}: {digest}\n')
        handle.write('    .section .bk_seed,"a",%progbits\n')
        for entry in entries:
            symbol = sanitize_ident(entry["vfs_path"])
            handle.write("    .balign 16\n")
            handle.write(f"    .global __bk_seed_{symbol}_start\n")
            handle.write(f"__bk_seed_{symbol}_start:\n")
            handle.write(f'    .incbin "{entry["artifact"]}"\n')
            handle.write(f"    .global __bk_seed_{symbol}_end\n")
            handle.write(f"__bk_seed_{symbol}_end:\n")


def write_catalog(entries, output):
    with open(output, "w", encoding="utf-8") as handle:
        handle.write("// Generated by gen_boot_seed_files.py — do not edit.\n")
        handle.write("#![no_std]\n#![allow(non_snake_case)]\n\n")
        handle.write("pub struct BootSeedFile {\n")
        handle.write("    pub path: &'static str,\n")
        handle.write("    bytes: unsafe fn() -> &'static [u8],\n")
        handle.write("}\n\n")
        handle.write("impl BootSeedFile {\n")
        handle.write("    pub unsafe fn bytes(&self) -> &'static [u8] {\n")
        handle.write("        unsafe { (self.bytes)() }\n")
        handle.write("    }\n")
        handle.write("}\n\n")
        for entry in entries:
            symbol = sanitize_ident(entry["vfs_path"])
            handle.write("extern \"C\" {\n")
            handle.write(f"    static __bk_seed_{symbol}_start: u8;\n")
            handle.write(f"    static __bk_seed_{symbol}_end: u8;\n")
            handle.write("}\n")
            handle.write(f"unsafe fn bytes_{symbol}() -> &'static [u8] {{\n")
            handle.write(
                f"    let start = &__bk_seed_{symbol}_start as *const u8;\n")
            handle.write(
                f"    let end = &__bk_seed_{symbol}_end as *const u8;\n")
            handle.write(
                "    let len = (end as usize).wrapping_sub(start as usize);\n")
            handle.write(
                "    unsafe { core::slice::from_raw_parts(start, len) }\n")
            handle.write("}\n\n")
        handle.write("pub static FILES: &[BootSeedFile] = &[\n")
        for entry in entries:
            symbol = sanitize_ident(entry["vfs_path"])
            path = json.dumps(entry["vfs_path"])
            handle.write(
                f"    BootSeedFile {{ path: {path}, bytes: bytes_{symbol} }},\n")
        handle.write("];\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--asm-out", required=True)
    parser.add_argument("--catalog-out", required=True)
    parser.add_argument("--file", action="append", default=[],
                        help="VFS path,artifact pair to embed")
    parser.add_argument("--layout", action="append", default=[],
                        help="app layout JSON (vfs_path/artifact, repeatable)")
    args = parser.parse_args()

    entries = collect_entries(args.file, args.layout)
    write_assembly(entries, args.asm_out)
    write_catalog(entries, args.catalog_out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
